# Generated by Django 4.1.7 on 2023-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_positive",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
